dist: bionic
sudo: required
language: node_js
node_js:
- stable
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 84.201.147.223
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
script: 'true'
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
